### ISSUE TITLE
Terrible, many bugs

### ISSUE THREAD

**Issue by antoniobrandao** [andresilvasantos/beatwhale#1]
The code is very buggy and too CPU intensive, crashed my computer repeatedly.

Also I didn't understand if it called beatwhale or birdify. Should be beatwhale because it crushed my CPU like a whale would.

**Comment by hbarroso** [comment]
@antoniobrandao I'm no the author but your comment is utterly useless. It doesn't provide any error report whatsoever that could be used by the author to fix it. If you want  to make yourself useful please state:

* Where is the code buggy ?
* What exactly is triggering the CPU intensiveness

Typical tuga....

**Comment by andresilvasantos** [comment]
Lol, you need to buy a better CPU instead of whining like a little girl!

**Comment by antoniobrandao** [comment]
loool a good joke is never invalid :hamster:
